### ISSUE TITLE
Spock doesn't git push

### ISSUE THREAD

**Issue by aerni90** [statamic/spock#10]
I followed all the issues and forum posts on The Lodge. I'm running the Spock with the [latest Pull request](https://github.com/statamic/spock/pull/9) provided by rrelmy. Spock is commiting the changes but it doesn't push them. I have to manually git push. Any lead on this issue? I would really love to have a working Spock instance!

I'm running the latest Statamic 2.8.2.

**My config**
```
environments:
  - production
  - prod
commands:
  - "git add {{ full_path }}"
  - "git commit -m '{{ url }} updated by {{ committer:username }}'"
  - "git push"
```

**Comment by jasonvarga** [comment]
Do you have anything in your logs? Spock should report any failures.

**Comment by aerni90** [comment]
Somehow it works not. This can be closed.
