### ISSUE TITLE
Can Spock also fire when forms are submitted?

### ISSUE THREAD

**Issue by bgarrant** [statamic/spock#12]
I finally got Spock setup but it does not fire on form submissions.  So when I git pull/push from local I always get the warning about the form yaml files and the MERGE junk if a form was submitted after the last content was saved. Any way to make Spock fire on form submissions as well?

**Comment by aerni90** [comment]
You would have to update your listener. Right now, this is not supported. However, I hope that the gents will update Spock in the future with more listeners. Like page deletes, collections etc. Maybe even configurable to customise the listener to the needs of the project.

**Comment by JesseLeite** [comment]
🖖

**Comment by bgarrant** [comment]
This does fire when forms are saved, but there is an issue as there is no username when a visitor submits a form without being logged in and Spock fails and you get a "Whoops, looks like something went wrong" error

**Comment by jasonvarga** [comment]
Good find. I'll open a separate issue.
