### ISSUE TITLE
Working with Spock v2 

### ISSUE THREAD

**Issue by pjhartin** [statamic/spock#14]
I noticed there was a v2 branch being worked on by @jasonvarga, so I pulled down the latest commit at https://github.com/statamic/spock/commit/89ddda602c9249ffd7594526e5ed7c0439cbcbe6 but can't seem to get it to run. Tests are passing, but I can't seem to get it to actually commit on save.

Has there been a change in the setup steps?

I've tried without a `spock.yaml` in `settings/addons` and also with the file there (as was previously in the current release version).

Can't seem to get it to work either way. 

I'm very interested in working with the functionality that has been added from the commit logs and would happily contribute if required, as we will be working with Statamic for the foreseeable future and a fully featured spock would be excellent.

**Comment by jackmcdade** [comment]
It requires a version of Statamic not released yet (2.10.0). Hang in there.

**Comment by JesseLeite** [comment]
🖖

**Comment by pjhartin** [comment]
Thanks for the update @jackmcdade. Loving the platform.
