### ISSUE TITLE
If triggered by an unauthenticated user, an error is thrown

### ISSUE THREAD

**Issue by jasonvarga** [statamic/spock#15]
The commit message contains the current user's username.
If they're logged out, there's no username to get. This could happen when using front-end forms.

We should change username to "unauthenticated user" or similar.

**Comment by bgarrant** [comment]
Front End forms work great when logged in, so we just need this little tweak for non-logged in use and we should be all set

**Comment by jasonvarga** [comment]
Fixed in 2.0.1
