### ISSUE TITLE
Statamic 1 backport / alternative?

### ISSUE THREAD

**Issue by ElliottJRo** [statamic/spock#2]
Is there something like this or is this re create-able on Statamic 1?

**Comment by jackmcdade** [comment]
v1 isn't built in a way modular enough to make this possible. Not quite like this anyway. You can check out [Revisions](http://statamic.com/learn/advanced-features/revisions) and the [Github Adapter](https://github.com/statamic/github-revisions) for a more CP-driven git experience.
