### ISSUE TITLE
Spock does not commit changes to assets yaml file

### ISSUE THREAD

**Issue by Alshie** [statamic/spock#23]
Adding a new post and uploading an asset with addition metadata causes Spock to commit the post but not the metadata changes in the asset container .yaml file.

Spoke with Jason on Discord and he confirmed "spock isn't listening for when assets are saved"

**Comment by jasonvarga** [comment]
Thanks!

**Comment by JesseLeite** [comment]
Hmm, these events don't cover you in this situation? 🤔 https://github.com/statamic/spock/blob/master/addons/Spock/SpockListener.php#L18-L24

May I ask what version of Statamic and Spock you are running?

**Comment by Alshie** [comment]
Ok, this is embarrassing. I was on latest Statamic, but somehow Spock 0.1.

Apologies. I have update to latest Spock and Asset Containers work fine. I'm really sorry guys.

**Comment by JesseLeite** [comment]
No worries, good to know!
