### ISSUE TITLE
Class 'Statamic\Addons\addons\Spock\SpockServiceProvider' not found

### ISSUE THREAD

**Issue by angelcnsk** [statamic/spock#27]
I'm trying to implement this add-on but I can not make it work, I just paste the addon folder and I get the following error:

FatalThrowableError in Application.php line 575:
Class 'Statamic \ Addons \ addons \ Spock \ SpockServiceProvider' not found

I have already added the lines indicated in the AddonServiceProvider.php file and added the spock.yaml file but it still does not work. I hope you can help me install and run this add-on. Thank you for the attention.

**Comment by jesseleite** [comment]
When you download Spock, make sure you drag the `Spock` folder into your `site/addons` folder.  The service provider should be at `site/addons/Spock/SpockServiceProvider.php`.

Also ensure you are running your site is running Statamic 2.10.0+ for the latest version of Spock.

**Comment by angelcnsk** [comment]
Thanks, it seems that the problem is that I had not updated to statamic 2.10 I managed not to mark an error, but I can not get it to execute the git commands. I copied and pasted the commands as indicated in the documentation but nothing happens when updating content. I appreciate the help.

**Comment by angelcnsk** [comment]
I am very grateful for your help, I had not understood that the serviceprovider is placed when custom commands are desired, I left only the spock.yaml file and it is already working correctly.
