### ISSUE TITLE
Spock can't handle ssh keys

### ISSUE THREAD

**Issue by grebbekevin** [statamic/spock#37]
Hee Guys,

We are new to spock and are having trouble with using spock to push to our git (bitbucket) repository. It is a private repository and needs an ssh key (or user and password) but how are we going to let spock use an ssh key and password? 

Please let me know.

**Comment by jesseleite** [comment]
Spock doesn't need to know credentials, as Spock doesn't make the connection to your remote.  It just runs `git add`, `git commit`, and `git push` commands for you, as a CLI user would.  You need to ensure connection to your remote is properly setup in your project.  If you can SSH in yourself and run `git push` successfully, then Spock should be able to `git push` as well.

**Comment by jesseleite** [comment]
Hope that helped!  Closing this for now, feel free to re-open if need to.
