### ISSUE TITLE
Fix Tests

### ISSUE THREAD

**Issue by edalzell** [statamic/spock#45]
<img width="416" alt="image" src="https://user-images.githubusercontent.com/6069653/70570408-b23e9180-1b50-11ea-8779-fa4846a55dc9.png">

**Comment by jasonvarga** [comment]
Here I thought you were opening a pull request that fixed the tests.

**Comment by edalzell** [comment]
Yup, will be doing it, but wanted to record it before I forgot.

**Comment by edalzell** [comment]
client wasn't on most recent version
