### ISSUE TITLE
Make spock show up in the Addons list

### ISSUE THREAD

**Issue by MerlinBB** [statamic/spock#8]
Hey guys,

I'm just trying to setup Spock, but it doesn't seem to be appearing in my list of add-ons in the control panel so I guess I'm doing something wrong.

Fold structure looks like so:

![image](https://cloud.githubusercontent.com/assets/3215478/22068131/ecdebafa-dd8b-11e6-8e5a-b4b5e65d0168.png)

Any ideas where I'm going wrong?

Thanks!

**Comment by jackmcdade** [comment]
Did you try Refreshing the Addon list?

**Comment by MerlinBB** [comment]
Yep, but still appearing empty...

**Comment by jackmcdade** [comment]
I don't think it's configured to show up, now that I think of it. I would just follow the docs and edit the settings by hand. It should work 👍

**Comment by MerlinBB** [comment]
ahhha, that would explain it then, cheers!

**Comment by jackmcdade** [comment]
🍻
